# Generated by Django 4.1 on 2022-08-21 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meeting", "0002_meeting_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Modified_By",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
